### ISSUE TITLE
Custom build for PhantomJS question

### ISSUE THREAD

**Issue by jchatard** [marcelduran/yslow#119]
Hi!

I'm have everything set up _and_ working. I want to create some custom _rules_ and _rule sets_ to test a few things using `PhantomJS`. So I downloaded `yslow` sources, did a `make phantomjs` and ran:

```
phantomjs yslow.js --info basic http://www.yahoo.com
```

This is working. So I decided to create a new dummy `rule` and `ruleset` using the `sample.js` file content which, as of now is made of:

``` javascript
YSLOW.registerRule({
   id: 'foo-rule1',
   name: 'Sample Test #1',
   info: 'How simple is that?',

   lint: function (doc, cset, config) {
       return {
           score: 90,
            message: 'close but no cigar',
          components: ['element1']
       };
   }
});

YSLOW.registerRuleset({
   id: 'foo',
   name: 'Foobar Ruleset',
   rules: {
       'foo-rule1': {}
   },
   weights: {
       'foo-rule1': 3
   }
});
```

So to use this new build, I re-run `make phantomjs`, done! And re-run this (same as earlier):

```
phantomjs yslow.js --info basic http://www.yahoo.com
```

Please note, that I know that I'm not _calling_ my custom ruleset (which I should by using the `-r` flag), but the point is that nothing happens. The process starts, but never nor _ends_ nor _quits_ with an error.

The not intended behavior that I can describe is: as soon as I create new rules and/or new rule sets in `sample.js` or any other file in the directory `src/common/rulesets` it _seems_ like the resulting build is not working anymore.

So I'm kind of stuck right now. If anyone has an idea, it would be really helpful!

Note that I did try using `yslow` head and tag 3.1.8 as well, no change.

Did I miss something?

Cheers,
Jérémy

**Comment by soulgalore** [comment]
Hi @jchatard , try with outputting messages to the console to see what's wrong:

<pre>
phantomjs yslow.js --info basic -c 2 http://www.yahoo.com 
</pre>

Best
Peter

**Comment by jchatard** [comment]
Here's what I've got:

``` json
{
    "message": "RAPID WARNING: Specified module not in DOM: default-p_30345940-bd"
}
{
    "message": "RAPID WARNING: Specified module not in DOM: default-p_30345967-bd"
}
```

**Comment by soulgalore** [comment]
ok :) I have a working example here:
https://github.com/sitespeedio/yslow/blob/master/src/common/rulesets/ruleset_sitespeed.js

but it is quite much extra things.

**Comment by jchatard** [comment]
Thanks @soulgalore!

Ok, here's what I've done, re-clone `yslow` to get clean sources, just in case.

Then, copy https://github.com/sitespeedio/yslow/blob/master/src/common/rulesets/ruleset_sitespeed.js in `src/common/rulesets` which ends up like this:

`src/common/rulesets/ruleset_sitespeed.js`

Let's say I want to use this ruleset:

``` javascript
YSLOW.registerRuleset({
    id: 'sitespeed.io-desktop',
    name: 'Sitespeed.io desktop rules',
    ...
```

I guess the `-r` argument has to be the `id` of the ruleset, so `sitespeed.io-desktop`. Am I right?

And run:

```
➜  yslow git:(master) ✗ make phantomjs 
building PHANTOMJS...
done
➜  yslow git:(master) ✗ cd build/phantomjs 
➜  phantomjs git:(master) ✗ phantomjs yslow.js -r sitespeed.io-desktop --info basic -c 2 http://www.yahoo.com 
{
    "message": "RAPID WARNING: Specified module not in DOM: default-p_30345940-bd"
}
{
    "message": "RAPID WARNING: Specified module not in DOM: default-p_30345967-bd"
}
^C
➜  phantomjs git:(master) ✗ 
```

So then I tried this:

```
➜  yslow git:(master) ✗ make pkg-phantomjs
building PHANTOMJS...
done
packaging PHANTOMJS...
done
➜  yslow git:(master) ✗ cd pkg/phantomjs/3.1.8 
➜  3.1.8 git:(master) ✗ ls
yslow.js
➜  3.1.8 git:(master) ✗ phantomjs yslow.js -r sitespeed.io-desktop --info basic -c 2 http://www.yahoo.com 
{"message":"TypeError: 'undefined' is not an object (evaluating 'q.prototype.getPref=function(s,r){return this.prefs.hasOwnProperty(s)?this.prefs[s]:r}')","stacktrace":[{"file":"phantomjs://webpage.evaluate()","line":1,"function":"anonymous"},{"file":"phantomjs://webpage.evaluate()","line":2,"function":""},{"file":"phantomjs://webpage.evaluate()","line":2,"function":""}]}
{"message":"TypeError: 'null' is not an object (evaluating 'j.failures')","stacktrace":[{"file":"yslow.js","line":5,"function":""},{"file":":/modules/webpage.js","line":281,"function":""}]}
{
    "message": "RAPID WARNING: Specified module not in DOM: default-p_30345940-bd"
}
{
    "message": "RAPID WARNING: Specified module not in DOM: default-p_30345967-bd"
}
^C
➜  3.1.8 git:(master) ✗ 
```

I'm pretty sure I'm missing something which is obvious for you :-)

Thanks!

**Comment by soulgalore** [comment]
Hi again @jchatard ,
strange, what does the RAPID WARNING actually means? This is exactly how I do it on my box:

<pre>
make phantomjs
phantomjs build/phantomjs/yslow.js -r sitespeed.io-desktop http://www.yahoo.com
</pre>

<pre>
phantomjs --version
1.9.7
</pre>

Best
Peter

**Comment by jchatard** [comment]
Hmm, doing it your way works. That's really strange.

I'll double check if I made any syntax error and eventually reopen in case of trouble. I'll now try to implement my custom rules.

Thank so much for the help!

Cheers,
Jérémy
