### ISSUE TITLE
YSlow is broken after update to Firefox 36.

### ISSUE THREAD

**Issue by squareplanetdesign** [marcelduran/yslow#142]
The YSlow tab is selectable in Firebug and loads the YSlow application, but none of the buttons or links are responsive on the YSlow app itself.

For example:

1) I click on the "Run Test" button.
2) There is no response.

Another example:

1) I check the  "Autorun YSlow each time a web page is loaded"
2) Refresh my tab
3) Tests are not run and the checkbox is unchecked again.

**Comment by astik** [comment]
Same problem here :
Firefox 36 + Firebug 2.0.8 + YSlow 3.1.8 on Ubuntu 14.04.1 and also same version on MacOSX 10.8.4 (was worging great 5 minutes ago before upgrading from Firefox 35.0.1).

Go the same behavior as described by @squareplanetdesign ... also, i can add that I'm not able to change the YSlow tab (grade, components, ...) but I'm able to switch between Firebug tabs.

**Comment by BioFa8** [comment]
Same problem:
Firefox 36 + Firebug 2.0.8 + YSlow 3.1.8 on Windows 7

**Comment by vamsitekuru** [comment]
I do have the same problem.None of my Yslow tabs are working after upgrade.

**Comment by bryanrasmussen** [comment]
same FF 36 + Firebug 2.0.8 + Yslow 3.1.8 + Mac OS X Yosemite.

**Comment by paquettej** [comment]
Same issue here. Any eta on a fix?

**Comment by hostz-frank** [comment]
BROKEN  :-(
Firefox 36 + Firebug 2.0.8 + YSlow 3.1.8 on Linux

**Comment by astik** [comment]
Upgrading to firefox 36.0.1 did not fix the problem ='(

**Comment by ericfpavoni** [comment]
Same Problem: FF 36.0.1, Firebug 2.0.8 , Yslow Last Version.

**Comment by fabswt** [comment]
Same with FF 36.0.1, Firebug 2.0.8. YSlow 3.1.8 . Tried disabling all other plugins just in case but that did not fix it.

**Comment by photocurio** [comment]
same FF 36 + Firebug 2.0.8 + Yslow 3.1.8 + Mac OS X Yosemite.

**Comment by imaging4design** [comment]
Yep .. waiting for the bug fix ... was a good tool ...

**Comment by nacoleman** [comment]
need yslow! cmon firefox

**Comment by pascal-stella** [comment]
Hello I confirm this problem
FF 36.0.1 + FB 2.0.8 + YSlow 3.1.8
Ubuntu + Gnome

**Comment by ryanhar** [comment]
Also occurring for me. Downgraded to FF 35 for now.

**Comment by sorinpohontu** [comment]
- Confirmed on FF 36.0.1, Mac OS X 10.9

**Comment by myheartwillgoon** [comment]
浏览器内核升级至gecko 36,不兼容了.能否更新修复一下....

**Comment by nurbek-ab** [comment]
90 open issues, the project was last updated a year ago. I think it's abandoned.

**Comment by bronson** [comment]
Yep, utterly broken on FF 36.  Downgrading to 35 worked: https://support.mozilla.org/en-US/kb/install-older-version-of-firefox

Agreed, right now YSlow looks like a dead project.  Anyone know of a good alternative?  https://developers.google.com/speed/pagespeed/insights is OK but feels noisier.

**Comment by toprakcagatay** [comment]
FF 36.0.1 YSlow 3.1.8 Ubuntu 14.04 LTS 
same problem.

**Comment by edjon2000** [comment]
Firefox 36.0.4 Firebug 2.0.8 + YSlow 3.1.8 on Windows 8.1
Unable to select tabs e.g. Home, Grade etc after loading components it moves to Grade tab and sticks there also unable to select filter by and vertical tabs down the page and unable to change or edit rulesets

**Comment by cmeans** [comment]
FF 36.0.4 Firebug 2.0.8 + YSlow 3.1.8 on Windows 7

All tabs and links in YSlow panel non-functional.

This has been true for the last two or more major version changes of Firefox.

**Comment by bronson** [comment]
Learn from my fail...   After downloading 35, go into about:config and set these:

```
app.update.auto - false
app.update.enabled - false
app.update.silent - false
```

Otherwise it won't take long for FF to break YSlow again.

**Comment by squareplanetdesign** [comment]
I've been doing some investigation. I managed to get the chrome debugger running and found what looks like the problem:

```
Error: Exposing privileged or cross-origin callable is prohibited
```

gets thrown every time I click any of the buttons.

Looking into what causes this issue, I found some notes about the browser development team removing the **exposedProps** support which was used in earlier Firefox version to expose stuff from privileged code (extensions) to sand-boxed code.  

The current firebug extension use a different model for exposing these kinds of things using lib/firebug/wrapper module and it looks like there have been a lot of architectural changes to firebug since the yslow plugin was last updated in that its been converted to a module based system and this plugin is now clearly relying on legacy support that is getting long in the tooth.

I have been trying to figure out a patch, but don't really have enough experience with extension development and debugging yet.  I was wondering if any of the contributors here or anyone else following this knows something about setting up the build and debugging for these extension to help me get started.

**Comment by marcelduran** [comment]
Hi,

Sorry, I have been busy with work and other projects lately. The point is it's been a while I'm not following Firefox development nor Firebug. That being said, looks like there was some change in FF and/or FB that affected YSlow. Looking at glance at the error message, looks like some CSP enforcement is causing YSlow to be an offender. YSlow has pretty old code style which has lots of inline script such as onclick="some_js()". If anyone with FF/FB devel knowledge could at least take a look at this I'm more than happy to merge and push a new version to Mozilla Addons.
Thanks for reaching out and again sorry for not being watching issues so close.

**Comment by bronson** [comment]
Lovely.  FF 35 just updated itself to 36 even though I had all three settings set to false.

I give up.  Just too much breakage.  So long Firefox, you were once great.

**Comment by ghost** [comment]
still doesnt work on ff 38 but noticed on chrome its a standalone add on and on ff its inside firebug myba @marcelduran could try and separate it from firebug like how it is on chrome?

**Comment by diegocard** [comment]
Not working on FF 38.0.5, and the panel is not even available on Firebug 3 beta

**Comment by hostz-frank** [comment]
Guys, I use YSlow without any problems as extension in most recent versions of Chromium/ Chrome. It's more fun to simply switch the browser and have it working than following this thread :-)

**Comment by anant-lelesys** [comment]
Not working on FF 39.0 + Firebug 2.0.11

**Comment by raffikazanjian** [comment]
Is there an alternative?

**Comment by Rubel-hossain** [comment]
I Have Solved The Problem . Firebug Works Properly in mozilla update verson by the way .
http://stackoverflow.com/questions/40800173/firebug-is-not-working-with-firefox-version-50-0/42218128#42218128
