### ISSUE TITLE
The Safari extension doesn't work at all

### ISSUE THREAD

**Issue by grimneko** [marcelduran/yslow#170]
Sitting on a OS X 10.11.2 Mini here and Safari 9.0.2 tries to run the extension. But beyond showing me the little button I can't get him to do anything. Tried several pages but never go any response from the extension; I can click it but nothing ever happens.

**Comment by kudit** [comment]
I'm having a similar issue.  Could it be that the bookmarklet is set to use http and the site is on https?

**Comment by CriticalNoob** [comment]
Same here, anything new ?

**Comment by bstillman** [comment]
Same here. Button appears but nothing happens when clicking it.

**Comment by Yerrak** [comment]
+1

**Comment by CriticalNoob** [comment]
The problem exist for 3 months and still no answer... doesn't sound good.

**Comment by frankarensmeier** [comment]
+1

**Comment by CriticalNoob** [comment]
I guess yslow extension isn't supported anymore. No update for 2 year and nobody seems to be around anymore... Time to move on guys.

**Comment by sparky672** [comment]
I can't get it to work either... I get some kind of error message about not being able to retrieve anything.  I can't get the exact error message now because I cannot get yslow to pop up anymore.

**Comment by daluu** [comment]
What was the resolution? I see this was closed. Closed to "move on" from this forsaken tool/project (in terms of Safari support)? If so, should have mentioned a note on it. Closing usually means fixed or not a bug, and should indicate reason for the close.
