### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'args.length')

### ISSUE THREAD

**Issue by spagu** [marcelduran/yslow#175]
# phantomjs yslow.js --help

TypeError: undefined is not an object (evaluating 'args.length')

  yslow.js:5 in global code
^C
# phantomjs -v

2.0.0

**Comment by emakeiv** [comment]
instead of 
`phantom.args`
use
`system = require('system'), 
  args = system.args,
`
http://phantomjs.org/api/phantom/property/args.html

**Comment by cdolek** [comment]
@Codtankist could you please give a usage example for this?

**Comment by outwitevil** [comment]
@cdolek I don't know if you still need this but I got it working and maybe this will help other people.
Taken from the top of my yslow.js file:

``` javascript
  /**
 * Copyright (c) 2012, Yahoo! Inc.  All rights reserved.
 * Copyrights licensed under the New BSD License. See the accompanying LICENSE file for terms.
 */
  var i, arg, page, urlCount, viewport, webpage = require("webpage"),
  system = require('system'),
  args = system.args,
  len = args.length,
  urls = [],
```

You have to insert the line that starts with system = require('system') and change the line args = phantom.args to args = system.args
Might be worth noting this is for phantomjs 2.1.1

**Comment by spagu** [comment]
works with 2.1 
thanks

**Comment by cdolek** [comment]
Thanks!

**Comment by juniorriau** [comment]
Hi

i have follow the changes above, but i got FAIL to load undefined with / without https. but with http, i got output
![image](https://user-images.githubusercontent.com/3606652/36940551-af380380-1f77-11e8-8c9c-16e9430de60a.png)
