### ISSUE TITLE
Permission denied when make pkg

### ISSUE THREAD

**Issue by aiddroid** [marcelduran/yslow#195]
allen@MacBookPro  ~/www/yslow:  make pkg-phantomjs
building PHANTOMJS...
done
packaging PHANTOMJS...
/bin/sh: build/phantomjs/yslow.js: Permission denied

**Comment by amake** [comment]
You need to have [yuicompressor](https://github.com/yui/yuicompressor) installed and available on your PATH as `yuicompressor`.
