### ISSUE TITLE
CDN & Virus

### ISSUE THREAD

**Issue by niz91** [marcelduran/yslow#38]
Hello,
sorry for my english.

i used yslow for analysing my website (shoppingfashion.fr)

in the cdn section, yslow offer me to add cdn and i accepted but i think this cdn have 2 viruses (http://cdn.tynt.com/tc.js, http://whos.amung.us/pingjs/?ETC...) you can see a report here :http://www.malware-control.com/statics-pages/63e3aa7d035afa698028dacf42ba7e1e.php

So how can i remove my website from this cdn?

thank you

**Comment by marcelduran** [comment]
When YSlow suggests to add a certain domain as a CDN it means that domain will be "considered as a CDN" for that particular instance of YSlow in your browser, so YSlow CDN rule won't complain if components found in your page (URLs) are hosted in such domain.
To remove domains from your YSlow CDN custom list, look for `extensions.yslow.cdnHostnames` property on _Options_ (Chrome) or _about:config_ (Firefox), [more info](https://github.com/marcelduran/yslow/wiki/FAQ#wiki-faq_cdn)

**Comment by niz91** [comment]
thank you problem resolved
