### ISSUE TITLE
Does not load with FireBug 1.10.1

### ISSUE THREAD

**Issue by hillsrobin** [marcelduran/yslow#46]
YSlow 3.1.0 does not load as a tab in FireBug 1.10.0.

This issue only occurs with this version of FireBug as I rolled back to 1.9.2 and YSlow appears correctly.

**Comment by marcelduran** [comment]
fixed and released, thanks ff addon reviewers
https://twitter.com/yslow/status/225152412044890112
https://addons.mozilla.org/en-US/firefox/addon/yslow/
