### ISSUE TITLE
Does not work with Firebug 1.10.0 in Firefox 13.0.1

### ISSUE THREAD

**Issue by webstylr** [marcelduran/yslow#47]
Since Firebug updated itself to Version 1.10.0, YSlow doesn't do a thing anymore. Clicking the YSlow icon, sometimes open a garbled firebug panel, but most of thime, nothing happens.

Someone opend a bug for firebug for this issue, so i thought i rather file the issue here.
http://code.google.com/p/fbug/issues/detail?id=5693

Is there a way that i can provide you with better debug/bug info?

I'm using the addon from addons.mozilla and run firefox/YSlow on linux (ubuntu).

**Comment by marcelduran** [comment]
Thanks for the catch, could you please open an issue at github.com/marcelduran/yslow or better yet fix the problem and send me a pull request? I'd be more than happy to merge such fix. 

## Best,

@marcelduran

**Comment by marcelduran** [comment]
fixed, see issue #46
