### ISSUE TITLE
YSLOW.firefox.Preference.getPrefList possibly causing Firefox slowdowns

### ISSUE THREAD

**Issue by mbrubeck** [marcelduran/yslow#49]
https://bugzilla.mozilla.org/show_bug.cgi?id=777397 was reported by a Firefox user experiencing frequent browser hangs.  Profiling with the Gecko Profiler showed a large amount of time spent in YSlow 3.1.2's getPrefList function, called by YSLOW.firefox.startup.

I notice that YSLOW.firefox.startup calls itself repeatedly in a timer loop until it successfully registers with Firebug.  Could this be going wrong somehow, causing this loop to continue forever?   Could this be mitigated by moving the getPrefList call out of the loop, and/or aborting if the loop has continued too long?

**Comment by marcelduran** [comment]
Attempt to fix https://bugzilla.mozilla.org/show_bug.cgi?id=777397

Just removed the unnecessary getPrefList block and increased startup timeout:  
https://github.com/marcelduran/yslow/commit/da3a53c21dbb9651e967a74a9e96a720796a0050
