### ISSUE TITLE
name of the preference extensions.yslow.beaconInfo not the same as used in documentation

### ISSUE THREAD

**Issue by mtolk** [marcelduran/yslow#5]
In the YSlow documentation( http://developer.yahoo.com/yslow/help/beacons.html#version2 ) the preference extensions.yslow.beaconInfo is mentioned. This is inconsistent with the preference name used in the code.

In the code /src/common/view.js line 413
     info = pref.getPref('info', 'basic'),

This uses the preference extensions.yslow.info.

I'm not sure if the documentation or the code needs changing.

**Comment by marcelduran** [comment]
fixed, the correct was beaconInfo, the issue is #5 not #7
