### ISSUE TITLE
PhantomJS: yfavicon rule appear not to work with phantomjs

### ISSUE THREAD

**Issue by soulgalore** [marcelduran/yslow#52]
Running on Mac OS X:

<pre>
phantomjs yslow.js http://www.facebook.com
</pre>

gives the following output:

<pre>
...
"yfavicon":{"score":95,"message":"Favicon is not cacheable","components":[]}
...
</pre>

and then later in the output, it seems like the size is 0 & no response headers:

<pre>
{"type":"favicon","url":"http\u00253A\u00252F\u00252Fstatic.ak.fbcdn.net\u00252Frsrc.php\u00252Fyi\u00252Fr\u00252Fq9U99v3_saj.ico","size":0,"resp":null,"headers":{"response":{}}}
</pre>

Checking the header in the browser, it gives me:

<pre>
Cache-Control   max-age=2592000
</pre>

Get the same with all sites I have tested. Anyone else that have this problem?

**Comment by soulgalore** [comment]
Ok, the thing is when populating the components in the phantomjs/controller, the favicon (and a couple of other types of requests, like Google fonts) hasn't been fetched by PhantomJS,meaning there is no request/response for it.  

Did a fix for it in https://github.com/soulgalore/yslow doing a XMLHttpRequest per asset not existing, but think it could be done cleaner, so not sending a pull.

**Comment by marcelduran** [comment]
thanks, will take a look any time. currently swamped with twitter stuff,
sorry.

@marcelduran

**Comment by soulgalore** [comment]
yes understand, I will clean up my fix and send a pull and then when you have time you can check how you can make it cleaner.
