### ISSUE TITLE
isETagGood for IIS 7.0+

### ISSUE THREAD

**Issue by NanoCaiordo** [marcelduran/yslow#61]
http://technet.microsoft.com/en-us/library/ee619764(v=WS.10).aspx
"In IIS 7.0, the metabase change number of 0 is the default setting and cannot be modified."

This will make the default IIS 7.0+ ETAG CDNs compatible as Timestamp:0 can be used across multiple IIS CDNs.

```
- var reIIS = /^[0-9a-f]+:[0-9a-f]+$/,
+ var reIIS = /^[0-9a-f]+:([1-9a-f]|[0-9a-f]{2,})$/,
```

**Comment by NanoCaiordo** [comment]
Any news on this one?

Cheers

**Comment by marcelduran** [comment]
can you send me a pull request? I'm kind of swamped right now, but I'll try my best to merge and get it released.
Thanks
