### ISSUE TITLE
'Run test' btn not working in FB 1.12b4 + FF 24.0a2

### ISSUE THREAD

**Issue by scheinercc** [marcelduran/yslow#81]
I can't activate YSlow any more. Pressing the 'Run test' btn has no effect, subtabs "Home", "Grade", etc. and "Printable View" are not working either.

-- System: FF24.0a2/update 2013-07-19, Firebug 12.0.b4, MacOS X 10.7.5

Just created a new profile and installed only FB beta and YSlow and also informed the FB folks about it: https://groups.google.com/forum/#!topic/firebug/kepp1Zh4rN4

Cheers,
Albert

**Comment by SebastianZ** [comment]
Just to be clear, the Firebug version is 1.12b4 and can be downloaded from [addons.mozilla.org](https://addons.mozilla.org/firefox/downloads/file/222152/firebug-1.12.0b4-fx.xpi?src=dp-btn-devchannel).

Sebastian

**Comment by marcelduran** [comment]
fixed, see issue #82 thanks
