### ISSUE TITLE
YSLOW does not work in Firebug 1.12beta

### ISSUE THREAD

**Issue by sroussey** [marcelduran/yslow#82]
I'm on the Firebug team, and wanted to let you know that YSlow is not working on the newest version of Firebug.

**Comment by marcelduran** [comment]
Any recent major change? I mean, haven't touched YSlow for Firebug for a while.
This is how YSlow gets into Firebug panel: https://github.com/marcelduran/yslow/blob/master/src/firefox/chrome/content/yslow-firebug.js

Could you please quickly sanity check?

Thanks

**Comment by lkraav** [comment]
Indeed, I'm also seeing that YSlow is not activating on FB 1.12 beta

**Comment by sroussey** [comment]
I'll see if I can fix it later today

**Comment by SebastianZ** [comment]
This is most probably due to the changes made in [issue 6477](https://code.google.com/p/fbug/issues/detail?id=6477).

Sebastian

**Comment by simonlindholm** [comment]
(That's a hidden issue, but essentially we changed the Firebug frame to be resource://firebugui/panel.html instead of chrome://firebug/content/panel.html, removing chrome privileges, and changing some subtle properties of the DOM in the process (like, I guess wrappers are slightly less transparent now).)

**Comment by janodvarko** [comment]
I have implemented a patch that should fix the problem.
https://github.com/marcelduran/yslow/pull/83

1) Firebug UI (panel.html) runs now with no extra privileges
2) API used from the panel.html scope must be exposed explicitly
see: https://blog.mozilla.org/addons/2012/08/20/exposing-objects-to-content-safely/ 
3) The attached patch also uses wrappers to expose the API

Please take a look and let me know what you think.

Honza

**Comment by marcelduran** [comment]
thanks @janodvarko jsut released new version [3.1.7](https://addons.mozilla.org/en-US/firefox/addon/yslow/versions/?page=1#version-3.1.7) with your fix.
